//exports from: ./bin/Debug/net6.0
#r @"bin\Debug\net6.0\CommandLine.dll"
#r @"bin\Debug\net6.0\Fantomas.Core.dll"
#r @"bin\Debug\net6.0\Fantomas.dll"
#r @"bin\Debug\net6.0\Fantomas.FCS.dll"
#r @"bin\Debug\net6.0\FSharp.Compiler.Service.dll"
#r @"bin\Debug\net6.0\FSharp.Core.dll"
#r @"bin\Debug\net6.0\FSharp.DependencyManager.Nuget.dll"
#r @"bin\Debug\net6.0\FsLexYacc.Runtime.dll"
#r @"bin\Debug\net6.0\Json2Fsharp.dll"
#r @"bin\Debug\net6.0\Microsoft.Build.Framework.dll"
#r @"bin\Debug\net6.0\Microsoft.Build.Tasks.Core.dll"
#r @"bin\Debug\net6.0\Microsoft.Build.Utilities.Core.dll"
#r @"bin\Debug\net6.0\Microsoft.NET.StringTools.dll"
#r @"bin\Debug\net6.0\Microsoft.Win32.SystemEvents.dll"
#r @"bin\Debug\net6.0\Myriad.Core.dll"
#r @"bin\Debug\net6.0\System.CodeDom.dll"
#r @"bin\Debug\net6.0\System.Configuration.ConfigurationManager.dll"
#r @"bin\Debug\net6.0\System.Drawing.Common.dll"
#r @"bin\Debug\net6.0\System.Resources.Extensions.dll"
#r @"bin\Debug\net6.0\System.Security.Cryptography.Pkcs.dll"
#r @"bin\Debug\net6.0\System.Security.Cryptography.ProtectedData.dll"
#r @"bin\Debug\net6.0\System.Security.Cryptography.Xml.dll"
#r @"bin\Debug\net6.0\System.Security.Permissions.dll"
#r @"bin\Debug\net6.0\System.Windows.Extensions.dll"
//
//no lib found
